#sudo: required

language: generic

services:
        - docker


before_install:
        - docker build -t mytravisci -f Dockerfile.dev .

script:
        - docker run -e CI=true mytravisci npm run test -- --coverage

